services:
  catalog-db:
    extends:
      file: docker-compose-base.yaml
      service: catalog-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=catalog
  catalog:
    extends:
      file: docker-compose-base.yaml
      service: catalog
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=dev
  catalog-dapr:
    extends:
      file: docker-compose-base.yaml
      service: catalog-dapr
    volumes:
      - "./dapr-config-minimal.yaml:/config.yaml"
  placement:
    image: "daprio/dapr"
    command: ["./placement", "-port", "50006"]
    ports:
      - "50006:50006"
volumes:
  catalog-db-data: