services:
  catalog-db:
    extends:
      file: docker-compose-base.yaml
      service: catalog-db
    ports:
      - 5432:5432
  catalog:
    extends:
      file: docker-compose-base.yaml
      service: catalog
    ports:
      - 8080:8080
  catalog-dapr:
    extends:
      file: docker-compose-base.yaml
      service: catalog-dapr
    volumes:
      - "./.dapr/dapr-config-minimal.yaml:/config.yaml"
      - "./.dapr/components:/components"
  placement:
    image: "daprio/dapr"
    command: ["./placement", "-port", "50006"]
    ports:
      - "50006:50006"
volumes:
  catalog-db-data: